acc, asset, metadata txn
proximax-foundry/web-wallet-vuejs pull request #479
Opened 2022-04-15 14:21 UTC by anakin001

2022-04-29 04:50 UTC, sleepyOwl14 approved these changes

2022-04-29 04:51 UTC, sleepyOwl14 requested changes
no restrict input

2022-04-29 04:53 UTC, anakin001 commented
> no restrict input

You mean chinese input and Other special characters?

2022-05-07 07:13 UTC, shinneng approved these changes

2022-05-11 02:39 UTC, sleepyOwl14 approved these changes

2022-05-11 02:39 UTC, merged