fix routing, remove account type filter(normal,multisig,others)
proximax-foundry/web-wallet-vuejs pull request #518
Opened 2022-06-10 10:04 UTC by anakin001

2022-06-15 08:59 UTC, shinneng approved these changes

2022-06-15 09:08 UTC, sleepyOwl14 commented on src/models/stores/chainSwapConfig.ts
>  }
this interface should be removed also

2022-06-15 10:35 UTC, sleepyOwl14 requested changes
need another message for extension not found, message not accurate.

2022-06-17 04:22 UTC, sleepyOwl14 approved these changes

2022-06-17 04:23 UTC, merged